# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_order: base.header, isocalendar
          config_timezone: Asia/Calcutta
          name: Full-year calendar
          filename: metrics.plugin.isocalendar.fullyear.svg
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

