name: metric
on:
  # Schedule daily updates
  schedule: [{ cron: "0 0 * * *" }]
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: fal4782
          config_timezone: Asia/Bangkok

          committer_message: "chore: update metrics"
          template: ""
          base: ""
          plugin_isocalendar_duration: full-year
